### ISSUE TITLE
Styling: figma to daisyui export

### ISSUE THREAD

**Issue by EvgeniiaVak** [DeXter-on-Radix/website#11]
Stefano's figma: https://www.figma.com/file/P7pfzKwJ4G6ClapXfl61D3/Dexter-UI?type=design&node-id=352-14130&mode=design&t=obQnc0e9mRl3IkDq-0 

Vlad's figma: https://www.figma.com/file/qushS15h87wjpoXaY6ND4W/DeXter-UI---refresh?node-id=501%3A1107&mode=dev

## MVP

- [x] #94
- [x] #95
- [x] #96
- [x] #97
- [x] #98
- [x] #133 
- [x] #103
- [x] #104
- [x] #81 
- [x] #120
- [x] #121
- [x] #122
- [x] #141

---

## Launch

- [ ] #123
- [x] #137

---

Maybe For the easy transformation from design idea to code, export some CSS variables. Example settings found [here](https://github.com/ernestoruperez/eo_design-tokens).

https://www.figma.com/file/P7pfzKwJ4G6ClapXfl61D3/Dexter-UI

**Comment by EvgeniiaVak** [comment]
@steferr you are free to change anything in this issue - title, description, etc

**Comment by steferr** [comment]
@EvgeniiaVak I played around a bit with the config files found in the [eo_design-tokens](https://github.com/ernestoruperez/eo_design-tokens). It will take some getting used to, but it's doable. The main issue i see is that when using Tokens Studio is that when you select layers in dev mode you see only raw values, so there is no way to understand what classes should be used. 

There are 2 ways to circumvent the issue:
1 - Traditional, manual redlining, but it's way too time consuming.
2 - Give editor access to the dev, so that she can open the Tokens Studio plugin and see the layer-token relationship (15$/month per editor seat)

What do you think?

**Comment by EvgeniiaVak** [comment]
I like the second option better.

**Comment by Kafkafrate** [comment]
I know this might be unpopular opinion but isn't it easier to just fill in manually the 10 colors we have and few text styles in a clean Figma File that we can share. It will be easier also to do the light version when you see the light version colors side by side. 

We don't have such a complicated UI, it's pretty minimal, plus the dashboard is one page. 
All these huge design systems complicate our lives in my opinion and slow us down. We don't need all shades of gray, blue, etc. Plus when new ones join it takes more time until they catch up with the design system.

**Comment by Kafkafrate** [comment]
If i look at the Daisy Theme generator we have much less variables to put in compared with these Figma Design Systems. 
Seems just faster to me making a theme manually just by looking at the elements in figma side by side.

**Comment by Kafkafrate** [comment]
To finalise the Dashboard UI first so that it looks balanced, and after that input into Daisy the values manually without using a Design System in Figma.

**Comment by EvgeniiaVak** [comment]
If it's not many colors, I agree with Kafkafrate

**Comment by EvgeniiaVak** [comment]
all done
