### ISSUE TITLE
Create a pair on AlphaDEX via DeXter

### ISSUE THREAD

**Issue by EvgeniiaVak** [DeXter-on-Radix/website#180]

**Comment by fliebenberg** [comment]
This issue was a feature request to be able to create a pair on AlphaDEX from Dexter. Any one can create a pair on AlphaDEX and the idea here was to provide an interface to do this on Dexter. I am not sure if this is still a need at the moment, so I would agree that we can remove the issue. It can always be added back again if there is a need in future.
