### ISSUE TITLE
Order book not fuly reflecting my limit order position

### ISSUE THREAD

**Issue by dcts** [DeXter-on-Radix/website#247]
I placed a limit order to buy 10'000 DEXTER at 3 XRD limit price. 

The order was filled ~5% (490 DEXTER).

10'000 - 490 = 9'510 DEXTER are still available to buy at 3 XRD price, yet the Order book shows only 4'009 DEXTER. My position is not fully reflected by the order book.

![order-book-issue](https://github.com/DeXter-on-Radix/website/assets/44790691/87c6e238-e3ca-477f-a071-e90babc032fd)

**Comment by fliebenberg** [comment]
This is an AlphaDEX backend issue that I will have a look at this week. The correct number is the one reflected in the order book and not the number in the order history. The AlphaDEX backend somehow gets out of sync with updating some orders in its database.

**Comment by fliebenberg** [comment]
I have identified the issue that is causing this bug. 
When a swap order is placed on AlphaDEX, there is no order receipt created (like for limit and market orders). The backend API was using new receipts to update the required orders in the database, so it was not updating the database on swaps. Although Dexter does not do any swap txs, there are other Alphadex users who do and whenever they were submitting swaps, the orderbook changed to refelct the trade, but the order details in the database did not change.
This issue will be fixed by an update to the AlphadEX backend api software.
For now I will keep this issue open until the api backend has been updated and we have tested it on Dexter.
