### ISSUE TITLE
xUSDC max amount input rounds values up instead of down

### ISSUE THREAD

**Issue by fliebenberg** [DeXter-on-Radix/website#486]
Issue raised on telegram.
Bug:
When I want to sell max xUSDC from my wallet, the amount is rounded up instead of down. AlphaDex supports 5 decimals for xUSDC, and I have 8 decimals of xUSDC in my wallet. So DeXter tries to sell up to 0.xxxx1 more than is in my wallet

Error from wallet:
InsufficientBalance { 
   requested: 562.70537, 
   actual: 562.705367 
}

**Comment by fliebenberg** [comment]
@dcts I assigned to you as you worked extensively on the new order input. I had a quick look, but could only find code where all amounts are rounded to 8 decimals. So could not find where it is rounded to 5 decimals.

**Comment by dcts** [comment]
# Final Bugreport (to follow bug bounty protocol)

The issue was that xUSDC coin has 6 decimals on [radix dashboard](https://dashboard.radixdlt.com/resource/resource_rdx1t4upr78guuapv5ept7d7ptekk9mqhy605zgms33mcszen8l9fac8vf/summary), but only 5 decimals specified on alphadex.

![](https://private-user-images.githubusercontent.com/44790691/350731647-bbfbdc54-0c54-4635-98a7-d962bb7e804a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2ODUwMTcsIm5iZiI6MTcyMTY4NDcxNywicGF0aCI6Ii80NDc5MDY5MS8zNTA3MzE2NDctYmJmYmRjNTQtMGM1NC00NjM1LTk4YTctZDk2MmJiN2U4MDRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDIxNDUxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyODA1MmRjNWMxYzViYTBlOTM2YjRmZjdlODViZDRjMjU2MWVlODcwMmQ5MmNjZDk3MzU2OWI0Y2RlYTAxMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OOWEyIfCZNWJ4UuJ_uv54FgDdmPgJyqSKy9xUvyA06M)

# The fix

- before sending any transaction, we now get the number of decimals on alphadex (could be different than the precision on radix dashboard) and always roundDown to that decimal places. 
- this can lead to dust in the wallet (which we cannot prevent) but prevents the transaction from failing
