### ISSUE TITLE
Transaction item with no description

### ISSUE THREAD

**Issue by EvgeniiaVak** [DeXter-on-Radix/website#82]
One question I have on the manifest, what's the second output shown here?
![263099094-a9ee1969-7bb8-4db4-a074-7ab154900cc9](https://github.com/DeXter-on-Radix/website/assets/27793901/17a90f06-7270-4736-92db-29bf197e3e02)

**Comment by EvgeniiaVak** [comment]
@Radstakes this is copied from https://github.com/DeXter-on-Radix/website/issues/8#issuecomment-1692364723, needs to be fixed, probably it's the fees, I'm not sure yet, but we definitely need to tell the user what is it.

**Comment by Radstakes** [comment]
@EvgeniiaVak - I wonder if this is the NFT receipt as it's shown as a deposit into my account?  Strangely there's no other balances or NFTs in my account apart from the ADEX token though.  @fliebenberg - any ideas on this?

**Comment by fliebenberg** [comment]
Yes, this is the order receipt NFT you receive when submitting a new order. The wallet does not show NFTs very well yet, so that is why you are not seeing it under the NFT section. But it is there, you can see it if you do a Gateway API call. Unfortunately even the RCNet dashboard does not display nfts yet, so you also cant check there. But it is there and it will have a better description once the wallet is updated to show the nft names etc.

**Comment by fliebenberg** [comment]
Closing this issue as it is not something we need to change in our App. It will be resolved when the wallet shows NFT data better.
